using Blazorise.Localization;
using Microsoft.AspNetCore.Components;
using SmartSkus.Shared.Dtos;
using SmartSkus.Core.Local.Interface;
using SmartSkus.Core.Local.Models;
using SmartSkus.Core.Services.Contracts;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace SmartSkus.Core.UI.Components
{
    public partial class AddInventoryComponent
    {
        #region Variables

        #region Parameter

        [Parameter]
        public AppModel AppModelObject { get; set; } = null!;

        [Parameter]
        public EventCallback<AppModel> AppModelObjectChanged { get; set; }

        [Parameter]
        public SettingsModel Settings { get; set; } = null!;

        //[Parameter]
        //public EventCallback<SettingsModel> SettingsChanged { get; set; }

        //[Parameter]
        //public IEnumerable<SkuModelDto>? Message { get; set; }

        #endregion

        #region Inject

        [Inject]
        ITextLocalizer<Translations> Localizer { get; set; } = null!;

        [Inject]
        IRepository Repository { get; set; } = null!;

        [Inject]
        public IInventoryService? InventoryService { get; set; }

        [Inject]
        public IMasterService? MasterService { get; set; }

        #endregion

        #region CascadingParameter

        [CascadingParameter]
        Blazorise.Size Size { get; set; }

        #endregion

        #endregion

        protected override async Task OnInitializedAsync()
        {
            await Task.Delay(0);
        }

        public async Task AddItem()
        {
            if (await validations.ValidateAll())
            {
                SkuModelDto skuModelDto = new()
                {
                    // Id - Autogenerated

                    ItemName = AppModelObject.SkuModelDtoObject.GenerateSku,
                    Attribute1 = AppModelObject.SkuModelDtoObject.Attribute1,
                    Attribute2 = AppModelObject.SkuModelDtoObject.Attribute2,
                    Attribute3 = AppModelObject.SkuModelDtoObject.Attribute3,

                    Description = AppModelObject.SkuModelDtoObject.Description,
                    Quantity = AppModelObject.SkuModelDtoObject.Quantity,

                    GenerateSku = AppModelObject.SkuModelDtoObject.GenerateSku
                };

                skuModelDto = await Repository.AddSkuModel(skuModelDto);

                AppModelObject.SkuModelDtoList.Add(skuModelDto);

                AppModelObject.SkuModelDtoObject = new();
                validations?.ClearAll();

                AppModelObject.SkuModelDtoList = (List<SkuModelDto>)await InventoryService.GetAll();

                AppModelObject.ItemDtoList = (List<ItemDto>)await InventoryService.GetAllItems();
                AppModelObject.ItemVariationDtoList
                    = (List<ItemVariationDto>)await InventoryService.GetAllItemVariations();

                AppModelObject.SelectedSkuModelDtoList = AppModelObject.SkuModelDtoList;
                AppModelObject.SelectedItemDtoList = AppModelObject.ItemDtoList;
                AppModelObject.SelectedItemVariationDtoList = AppModelObject.ItemVariationDtoList;

                await AppModelObjectChanged.InvokeAsync(AppModelObject);
            }
        }
    }
}